name: Build and Release
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Find JAR File
        id: find_jar
        run: echo "MOD_FILE=$(ls build/libs/*.jar | head -n 1)" >> $GITHUB_ENV

  release:
    name: Publish JAR and Upload to Modrinth
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.MOD_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@1.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ro29R42L
          file: ${{ env.MOD_FILE }}
          changelog: This release is from GitHub - ${{ github.event.release.body }}
          loaders: fabric
