name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]  # Current Java LTS
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: Build
        run: ./gradlew build
      
      - name: Capture build artifacts
        if: ${{ matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Upload to Modrinth
        if: success()  # Only run if previous steps are successful
        uses: cloudnode-pro/modrinth-publish@1.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ro29R42L  # Your Modrinth project ID
          file: build/libs/YourModFile.jar  # Replace with your actual file path
          changelog: |
            This version is from a GitHub commit/change. You can see the full details of the commit at [#commit](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})

            Commit Details:
            ${GITHUB_SHA}
          loaders: fabric  # Specify the loaders you want to support
          api-domain: api.modrinth.com  # Default API domain
